default: &default
  adapter: mysql2
  username: root
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: lolarmory_dev
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: lolarmory_test

production:
  <<: *default
  database: lolarmory_prod
  socket: /var/lib/mysql/mysql.sock
